### ISSUE TITLE
Filtered VGGSound file list?

### ISSUE THREAD

**Issue by miraodasilva** [guyyariv/TempoTokens#2]
![image](https://github.com/guyyariv/TempoTokens/assets/17463598/72c41407-64cd-421b-82d1-cc386fe292ff)
Hi,

First of all, really like the paper :) I think it presents an elegant solution and impressive results. As seen above, the paper mentions a filtered version of VGGSound, which seems like a really good idea since the dataset is usually quite noisy. I was wondering if you could share the file list for this filtered version (as a .csv, for example) ? I looked around in the repo, and the only list I could find was datasets/vggsound.csv, which seems to contain (almost?) the whole dataset, rather than the filtered version. Any help would be greatly appreciated. Thank you.

**Comment by guyyariv** [comment]
Hello, we appreciate your comment! :)
You can access the "constants/unmatch_videos.pkl" pickle file to find a list of YouTube IDs where the audio doesn't match the video. Please note that these YouTube IDs are only from a subset of vggsound's training set. By filtering out these videos, you'll obtain the training set that we used for our training.
