### ISSUE TITLE
AV-Align metric implementation

### ISSUE THREAD

**Issue by miraodasilva** [guyyariv/TempoTokens#3]
Hi,

Thanks again for responding to my previous issue. I was wondering if you plan to release the code to reproduce the AV-Align metric proposed in the paper? I looked through the repo and could not find any source code for this (apologies if I'm mistaken). I think it's a very interesting metric and would be important in trying to reproduce your results. Thanks!

**Comment by guyyariv** [comment]
Hello again :)
Yes, I will upload the code soon

**Comment by guyyariv** [comment]
https://github.com/guyyariv/TempoTokens/blob/master/av_align.py
