### ISSUE TITLE
Cannt download the BEATs_iter3+ (AS2M) (cpt2)

### ISSUE THREAD

**Issue by aleeyang** [guyyariv/TempoTokens#4]
` mkdir -p models/BEATs/ && wget -P models/BEATs/ -O "models/BEATs/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt" "https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D"
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/yang/.wget-hsts'. HSTS will be disabled.
--2024-03-30 12:01:55--  https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D
Resolving valle.blob.core.windows.net (valle.blob.core.windows.net)... 20.60.231.33
Connecting to valle.blob.core.windows.net (valle.blob.core.windows.net)|20.60.231.33|:443... connected.
HTTP request sent, awaiting response... 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
2024-03-30 12:01:56 ERROR 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature..
`

Can you provide other link?

**Comment by guyyariv** [comment]
It seems that the original link provided by the BEATS authors is currently broken: https://github.com/microsoft/unilm/tree/master/beats.

Therefore, I have uploaded the weights myself; feel free to use them: https://drive.google.com/drive/folders/1DZPDZTCyFyPSn4xcgqJlTWKBf5h-Fp5d?usp=sharing

**Comment by aleeyang** [comment]
thank you so much
