### ISSUE TITLE
Modification about configs/structure of the dataset folder

### ISSUE THREAD

**Issue by jiajiaxiaoskx** [guyyariv/TempoTokens#5]
A fancy work! I encountered an issue where data could not be found when I ran train.py. Your config file shows that the dataset files are divided into video/audio subfolders, but the subfolders in the dataset files you provided are not divided this way. I encounter errors similar to the following when running the code. 

FileNotFoundError: [Errno 2] No such file or directory: 'None/video/'

Thus, I am unsure how to modify the contents of the config file or the division of the dataset files. Could you show me how to edit the config file or change the division of the dataset subfolders? Or could you upload a dataset that matches the content of the config file?

Thanks!

**Comment by guyyariv** [comment]
Hi, thanks for your interest in our project. For me, when the ```path:``` in the config file is indeed set to the split (audio, video) vggsound folder, the process runs successfully.
