### ISSUE TITLE
Can I use AV-Align to asses video-to-audio generation?

### ISSUE THREAD

**Issue by BingliangLi** [guyyariv/TempoTokens#8]
Hi, I thinks the av-align score is a brilliant idea, I would like to ask does it make sense to asses V2A instead of A2V?

**Comment by guyyariv** [comment]
Hey, thank you! That makes sense to me, and a recent study has already addressed this (see https://arxiv.org/abs/2407.07464).

**Comment by BingliangLi** [comment]
Thanks!
